services:
    spbar.blog_post_form_type:
        class: SpBar\Bundle\BlogBundle\Form\Type\PostFormType
        tags:
            - { name: form.type, alias: spbar_blog_post }
        arguments: ["@spbar.blog_theme_manager"]

    spbar.blog_post_manager:
        class: SpBar\Bundle\BlogBundle\Model\PostManager
        arguments: ["@doctrine.orm.entity_manager"]