BlogUserBundle:
    resource: "@BlogUserBundle/Resources/config/routing.yml"
    prefix: /admin

BlogPostBundle:
    resource: "@BlogPostBundle/Resources/config/routing.yml"
    prefix: /

BlogReportBundle:
    resource: "@BlogReportBundle/Resources/config/routing.yml"
    prefix: /reports

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

logout:
    path: /logout
