security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: loginPage
                check_path: loginCheckPage
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        # - { path: ^/admin/post, role: [ROLE_AUTHOR, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        # # - { path: ^/admin/route, role: ROLE_SUPER_ADMIN}
        # - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        # - { path: ^/user/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/user, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default