security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:      [ROLE_USER]
        ROLE_AUTHOR:    [ROLE_USER, ROLE_AUTHOR]
        ROLE_ADMIN:     [ROLE_AUTHOR, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                invalidate_session: false
                target: /
            anonymous:    true

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/profile, roles: ROLE_USER}
        - { path: ^/profile/edit, roles: ROLE_USER}

        - { path: ^/register, role: ROLE_ADMIN }

        - { path: ^/posts/dashboard, roles: ['ROLE_AUTHOR', 'ROLE_ADMIN']}
        - { path: ^/posts/new, roles: ['ROLE_AUTHOR', 'ROLE_ADMIN']}
        - { path: ^/post/edit/, roles: ['ROLE_AUTHOR', 'ROLE_ADMIN']}
        - { path: ^/post/delete/, roles: ['ROLE_AUTHOR', 'ROLE_ADMIN']}

        - { path: ^/comment/delete/, roles: ROLE_ADMIN }
        - { path: ^/reports, roles: ROLE_ADMIN}
        
