security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_BLOG_ADMIN: [ROLE_BLOG_AUTHOR, ROLE_BLOG_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_BLOG_ADMIN, ROLE_BLOG_AUTHOR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: sp_user_login
                check_path: sp_user_login_check
                csrf_provider: form.csrf_provider
            logout:
                path: sp_user_logout
                target: sp_user_login
            anonymous: true

    access_control:    
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/blog/post/new, role: [ROLE_BLOG_AUTHOR] }
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
        # - { path: ^/user/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/user, role: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin/post, role: [ROLE_AUTHOR, ROLE_ADMIN, ROLE_SUPER_ADMIN] }
        # # - { path: ^/admin/route, role: ROLE_SUPER_ADMIN}

    acl:
        connection: default