#services:
#    user.example:
#        class: UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    blog_user.registration.form.type:
        class: Blog\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: blog_user_registration }

    blog_user.profile.form.type:
        class: Blog\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: blog_user_profile }

    blog_user.change_password.form.type:
        class: Blog\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: blog_user_change_password }          
