sp_blog_front_post_index:
    path: /
    defaults: { _controller: SpBarBlogBundle:Frontend/Post:index }

# sp_blog_front_post_authorPost:
#     path: /sp-{user}/posts/
#     defaults: { _controller: SpBarBlogBundle:Frontend/Post:authorPost }

sp_blog_front_post_singlePost:
    path: /{slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Post:singlePost }