sp_blog_publiccomment:
    resource: "@SpBarBlogBundle/Resources/config/frontend/public_comment.yml"
    prefix:   /comment

sp_blog_publicpost:
    resource: "@SpBarBlogBundle/Resources/config/frontend/public_post.yml"
    prefix:   /