sp_blog_publicpost_index:
    path: /
    defaults: { _controller: SpBarBlogBundle:Frontend/PublicPost:index }

sp_blog_publicpost_authorPost:
    path: /sp-{user}/posts/
    defaults: { _controller: SpBarBlogBundle:Frontend/PublicPost:authorPost }

sp_blog_publicpost_singlePost:
    path: /{slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/PublicPost:singlePost }